
//Set path to SmartSlog KP Library
#include <generic.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_MBOX 1
#define INCLUDE_PROPERTY_SECTIONPARAMETER 1
#define INCLUDE_PROPERTY_STARTUPDATESERVICEPAGE 1
#define INCLUDE_PROPERTY_SOCIALPROGRAMLATITUDECOORDINATE 1
#define INCLUDE_PROPERTY_PRESENTATIONURL 1
#define INCLUDE_PROPERTY_CONTENTURL 1
#define INCLUDE_PROPERTY_ORGANIZATION 1
#define INCLUDE_PROPERTY_PHOTOLONGITUDECOORDINATE 1
#define INCLUDE_PROPERTY_SECTIONSTARTTIME 1
#define INCLUDE_PROPERTY_VIDEOTITLE 1
#define INCLUDE_PROPERTY_PHOTOTHUMBNAILURL 1
#define INCLUDE_PROPERTY_ENDPRESENTATION 1
#define INCLUDE_PROPERTY_CURRENTSLIDENUM 1
#define INCLUDE_PROPERTY_STOPSEARCH 1
#define INCLUDE_PROPERTY_HOLDSACTIVITY 1
#define INCLUDE_PROPERTY_STARTSERVICEMODE 1
#define INCLUDE_PROPERTY_PHOTOLATITUDECOORDINATE 1
#define INCLUDE_PROPERTY_ACTIVITYTITLE 1
#define INCLUDE_PROPERTY_VOTEUPDATE 1
#define INCLUDE_PROPERTY_USERNAME 1
#define INCLUDE_PROPERTY_PHOTOURL 1
#define INCLUDE_PROPERTY_PHOTOTITLE 1
#define INCLUDE_PROPERTY_TIMESLOTACTUALDURATION 1
#define INCLUDE_PROPERTY_TOPIC_INTEREST 1
#define INCLUDE_PROPERTY_PASSWORD 1
#define INCLUDE_PROPERTY_PLACESLOTMINUSRATING 1
#define INCLUDE_PROPERTY_HASVIDEO 1
#define INCLUDE_PROPERTY_TIMESLOTTITLE 1
#define INCLUDE_PROPERTY_HASPRESENTATIONSERVICEURL 1
#define INCLUDE_PROPERTY_SECTIONACTUALSTARTTIME 1
#define INCLUDE_PROPERTY_SOCIALPROGRAMTITLE 1
#define INCLUDE_PROPERTY_PHONE 1
#define INCLUDE_PROPERTY_UPDATESERVICEINFORMATION 1
#define INCLUDE_PROPERTY_STARTCONFERENCE 1
#define INCLUDE_PROPERTY_PLACESLOTPLUSRATING 1
#define INCLUDE_PROPERTY_CURRENTSLIDECOUNT 1
#define INCLUDE_PROPERTY_PLACESLOTRATING 1
#define INCLUDE_PROPERTY_HASSERVICE 1
#define INCLUDE_PROPERTY_SECTIONTITLE 1
#define INCLUDE_PROPERTY_PERSONINFORMATION 1
#define INCLUDE_PROPERTY_CURRENTSLIDEIMG 1
#define INCLUDE_PROPERTY_NEXTTIMESLOT 1
#define INCLUDE_PROPERTY_TIMESLOTSPEAKERNAME 1
#define INCLUDE_PROPERTY_PLACEHASRELATION 1
#define INCLUDE_PROPERTY_STOPSERVICEMODE 1
#define INCLUDE_PROPERTY_PORT 1
#define INCLUDE_PROPERTY_PLACEHASPHOTO 1
#define INCLUDE_PROPERTY_PRESENTATIONTITLE 1
#define INCLUDE_PROPERTY_TIMESLOTPARAMETER 1
#define INCLUDE_PROPERTY_HASSECTION 1
#define INCLUDE_PROPERTY_FIRSTTIMESLOT 1
#define INCLUDE_PROPERTY_STARTVIDEO 1
#define INCLUDE_PROPERTY_STARTSEARCH 1
#define INCLUDE_PROPERTY_SOCIALPROGRAMPRESENTPLACESLOT 1
#define INCLUDE_PROPERTY_SERVICENAME 1
#define INCLUDE_PROPERTY_PLACELONGITUDECOORDINATE 1
#define INCLUDE_PROPERTY_NAME 1
#define INCLUDE_PROPERTY_PRESENTATIONTAGS 1
#define INCLUDE_PROPERTY_CITY 1
#define INCLUDE_PROPERTY_STARTPRESENTATION 1
#define INCLUDE_PROPERTY_CURRENTTIMESLOT 1
#define INCLUDE_PROPERTY_PHOTODESCRIPTION 1
#define INCLUDE_PROPERTY_SHOWSLIDE 1
#define INCLUDE_PROPERTY_IP 1
#define INCLUDE_PROPERTY_HASSERVICEPARAMETER 1
#define INCLUDE_PROPERTY_CURRENTSOCIALPROGRAM 1
#define INCLUDE_PROPERTY_UPDATEPRESENTATION 1
#define INCLUDE_PROPERTY_PHOTOMEDIUMURL 1
#define INCLUDE_PROPERTY_STOPVIDEO 1
#define INCLUDE_PROPERTY_ENDCONFERENCE 1
#define INCLUDE_PROPERTY_SERVICEDESCRIPTION 1
#define INCLUDE_PROPERTY_PLACEPARAMETER 1
#define INCLUDE_PROPERTY_TIMESLOTPERSON 1
#define INCLUDE_PROPERTY_NOTIFICATIONNUMBERPARAMETER 1
#define INCLUDE_PROPERTY_SHOWSUMMARYSLIDE 1
#define INCLUDE_PROPERTY_SOCIALPROGRAMLONGITUDECOORDINATE 1
#define INCLUDE_PROPERTY_STATUS 1
#define INCLUDE_PROPERTY_WLANMAC 1
#define INCLUDE_PROPERTY_TIMESLOTPRESENTATION 1
#define INCLUDE_PROPERTY_ACCOUNT 1
#define INCLUDE_PROPERTY_TIMESLOTDURATION 1
#define INCLUDE_PROPERTY_SECTIONDATE 1
#define INCLUDE_PROPERTY_AGE 1
#define INCLUDE_PROPERTY_UPDATEAGENDA 1
#define INCLUDE_PROPERTY_SEARCHTYPEPARAMETER 1
#define INCLUDE_PROPERTY_IMG 1
#define INCLUDE_PROPERTY_PRESENTSOCIALPROGRAM 1
#define INCLUDE_PROPERTY_HASAGENDASERVICEURL 1
#define INCLUDE_PROPERTY_PLACELATITUDECOORDINATE 1
#define INCLUDE_PROPERTY_PLACESLOTPRESENTPLACE 1
#define INCLUDE_PROPERTY_SERVICEINFORMATIONPARAMETER 1
#define INCLUDE_PROPERTY_LANGUAGE 1
#define INCLUDE_PROPERTY_PLACETITLE 1
#define INCLUDE_PROPERTY_HASPRESENTATION 1
#define INCLUDE_PROPERTY_CURRENTPRESENTATION 1
#define INCLUDE_PROPERTY_HASCONTEXT 1
#define INCLUDE_PROPERTY_STARTCONFERENCEFROM 1
#define INCLUDE_PROPERTY_SERVICESTATUS 1
#define INCLUDE_PROPERTY_FROMSERVICEPARAMETER 1
#define INCLUDE_PROPERTY_STOPUPDATESERVICEPAGE 1
#define INCLUDE_PROPERTY_SEARCHVARIABLEPARAMETER 1
#define INCLUDE_PROPERTY_PLACEDESCRIPTION 1
#define INCLUDE_PROPERTY_HASCLIENTURL 1
#define INCLUDE_PROPERTY_VIDEOURL 1
#define INCLUDE_PROPERTY_PLACEFOUNDINGDATE 1
#define INCLUDE_PROPERTY_CURRENTSECTION 1
#define INCLUDE_CLASS_SMARTROOM 1
#define INCLUDE_CLASS_PRESENTATION 1
#define INCLUDE_CLASS_CONFERENCENOTIFICATION 1
#define INCLUDE_CLASS_SEARCHACTIVITYPARAMETER 1
#define INCLUDE_CLASS_ACTIVITY 1
#define INCLUDE_CLASS_PROFILE 1
#define INCLUDE_CLASS_PERSON 1
#define INCLUDE_CLASS_CLIENTNOTIFICATION 1
#define INCLUDE_CLASS_SOCIALPROGRAMNOTIFICATION 1
#define INCLUDE_CLASS_WEBSERVERNOTIFICATION 1
#define INCLUDE_CLASS_DISCUSSIONSERVICE 1
#define INCLUDE_CLASS_SERVICE 1
#define INCLUDE_CLASS_PLACE 1
#define INCLUDE_CLASS_TIMESLOT 1
#define INCLUDE_CLASS_DSNOTIFICATIONPARAMETER 1
#define INCLUDE_CLASS_PRESENTATIONSERVICE 1
#define INCLUDE_CLASS_THING 1
#define INCLUDE_CLASS_CONTENTSERVICE 1
#define INCLUDE_CLASS_AGENDANOTIFICATION 1
#define INCLUDE_CLASS_SOCIALPROGRAM 1
#define INCLUDE_CLASS_PLACESLOT 1
#define INCLUDE_CLASS_CONFERENCESERVICE 1
#define INCLUDE_CLASS_ONLINEACCOUNT 1
#define INCLUDE_CLASS_PHOTO 1
#define INCLUDE_CLASS_SEARCHACTIVITY 1
#define INCLUDE_CLASS_NOTIFICATIONPARAMETER 1
#define INCLUDE_CLASS_SOCIALPROGRAMSERVICE 1
#define INCLUDE_CLASS_NOTHING 1
#define INCLUDE_CLASS_MICROPHONESERVICE 1
#define INCLUDE_CLASS_VIDEO 1
#define INCLUDE_CLASS_SECTION 1
#define INCLUDE_CLASS_CONTEXT 1
#define INCLUDE_CLASS_PRESENTATIONNOTIFICATION 1


#else

#define INCLUDE_PROPERTY_MBOX 0
#define INCLUDE_PROPERTY_SECTIONPARAMETER 0
#define INCLUDE_PROPERTY_STARTUPDATESERVICEPAGE 0
#define INCLUDE_PROPERTY_SOCIALPROGRAMLATITUDECOORDINATE 0
#define INCLUDE_PROPERTY_PRESENTATIONURL 0
#define INCLUDE_PROPERTY_CONTENTURL 0
#define INCLUDE_PROPERTY_ORGANIZATION 0
#define INCLUDE_PROPERTY_PHOTOLONGITUDECOORDINATE 0
#define INCLUDE_PROPERTY_SECTIONSTARTTIME 0
#define INCLUDE_PROPERTY_VIDEOTITLE 0
#define INCLUDE_PROPERTY_PHOTOTHUMBNAILURL 0
#define INCLUDE_PROPERTY_ENDPRESENTATION 0
#define INCLUDE_PROPERTY_CURRENTSLIDENUM 0
#define INCLUDE_PROPERTY_STOPSEARCH 0
#define INCLUDE_PROPERTY_HOLDSACTIVITY 0
#define INCLUDE_PROPERTY_STARTSERVICEMODE 0
#define INCLUDE_PROPERTY_PHOTOLATITUDECOORDINATE 0
#define INCLUDE_PROPERTY_ACTIVITYTITLE 0
#define INCLUDE_PROPERTY_VOTEUPDATE 0
#define INCLUDE_PROPERTY_USERNAME 0
#define INCLUDE_PROPERTY_PHOTOURL 0
#define INCLUDE_PROPERTY_PHOTOTITLE 0
#define INCLUDE_PROPERTY_TIMESLOTACTUALDURATION 0
#define INCLUDE_PROPERTY_TOPIC_INTEREST 0
#define INCLUDE_PROPERTY_PASSWORD 0
#define INCLUDE_PROPERTY_PLACESLOTMINUSRATING 0
#define INCLUDE_PROPERTY_HASVIDEO 0
#define INCLUDE_PROPERTY_TIMESLOTTITLE 0
#define INCLUDE_PROPERTY_HASPRESENTATIONSERVICEURL 0
#define INCLUDE_PROPERTY_SECTIONACTUALSTARTTIME 0
#define INCLUDE_PROPERTY_SOCIALPROGRAMTITLE 0
#define INCLUDE_PROPERTY_PHONE 0
#define INCLUDE_PROPERTY_UPDATESERVICEINFORMATION 0
#define INCLUDE_PROPERTY_STARTCONFERENCE 0
#define INCLUDE_PROPERTY_PLACESLOTPLUSRATING 0
#define INCLUDE_PROPERTY_CURRENTSLIDECOUNT 0
#define INCLUDE_PROPERTY_PLACESLOTRATING 0
#define INCLUDE_PROPERTY_HASSERVICE 0
#define INCLUDE_PROPERTY_SECTIONTITLE 0
#define INCLUDE_PROPERTY_PERSONINFORMATION 0
#define INCLUDE_PROPERTY_CURRENTSLIDEIMG 0
#define INCLUDE_PROPERTY_NEXTTIMESLOT 0
#define INCLUDE_PROPERTY_TIMESLOTSPEAKERNAME 0
#define INCLUDE_PROPERTY_PLACEHASRELATION 0
#define INCLUDE_PROPERTY_STOPSERVICEMODE 0
#define INCLUDE_PROPERTY_PORT 0
#define INCLUDE_PROPERTY_PLACEHASPHOTO 0
#define INCLUDE_PROPERTY_PRESENTATIONTITLE 0
#define INCLUDE_PROPERTY_TIMESLOTPARAMETER 0
#define INCLUDE_PROPERTY_HASSECTION 0
#define INCLUDE_PROPERTY_FIRSTTIMESLOT 0
#define INCLUDE_PROPERTY_STARTVIDEO 0
#define INCLUDE_PROPERTY_STARTSEARCH 0
#define INCLUDE_PROPERTY_SOCIALPROGRAMPRESENTPLACESLOT 0
#define INCLUDE_PROPERTY_SERVICENAME 0
#define INCLUDE_PROPERTY_PLACELONGITUDECOORDINATE 0
#define INCLUDE_PROPERTY_NAME 0
#define INCLUDE_PROPERTY_PRESENTATIONTAGS 0
#define INCLUDE_PROPERTY_CITY 0
#define INCLUDE_PROPERTY_STARTPRESENTATION 0
#define INCLUDE_PROPERTY_CURRENTTIMESLOT 0
#define INCLUDE_PROPERTY_PHOTODESCRIPTION 0
#define INCLUDE_PROPERTY_SHOWSLIDE 0
#define INCLUDE_PROPERTY_IP 0
#define INCLUDE_PROPERTY_HASSERVICEPARAMETER 0
#define INCLUDE_PROPERTY_CURRENTSOCIALPROGRAM 0
#define INCLUDE_PROPERTY_UPDATEPRESENTATION 0
#define INCLUDE_PROPERTY_PHOTOMEDIUMURL 0
#define INCLUDE_PROPERTY_STOPVIDEO 0
#define INCLUDE_PROPERTY_ENDCONFERENCE 0
#define INCLUDE_PROPERTY_SERVICEDESCRIPTION 0
#define INCLUDE_PROPERTY_PLACEPARAMETER 0
#define INCLUDE_PROPERTY_TIMESLOTPERSON 0
#define INCLUDE_PROPERTY_NOTIFICATIONNUMBERPARAMETER 0
#define INCLUDE_PROPERTY_SHOWSUMMARYSLIDE 0
#define INCLUDE_PROPERTY_SOCIALPROGRAMLONGITUDECOORDINATE 0
#define INCLUDE_PROPERTY_STATUS 0
#define INCLUDE_PROPERTY_WLANMAC 0
#define INCLUDE_PROPERTY_TIMESLOTPRESENTATION 0
#define INCLUDE_PROPERTY_ACCOUNT 0
#define INCLUDE_PROPERTY_TIMESLOTDURATION 0
#define INCLUDE_PROPERTY_SECTIONDATE 0
#define INCLUDE_PROPERTY_AGE 0
#define INCLUDE_PROPERTY_UPDATEAGENDA 0
#define INCLUDE_PROPERTY_SEARCHTYPEPARAMETER 0
#define INCLUDE_PROPERTY_IMG 0
#define INCLUDE_PROPERTY_PRESENTSOCIALPROGRAM 0
#define INCLUDE_PROPERTY_HASAGENDASERVICEURL 0
#define INCLUDE_PROPERTY_PLACELATITUDECOORDINATE 0
#define INCLUDE_PROPERTY_PLACESLOTPRESENTPLACE 0
#define INCLUDE_PROPERTY_SERVICEINFORMATIONPARAMETER 0
#define INCLUDE_PROPERTY_LANGUAGE 0
#define INCLUDE_PROPERTY_PLACETITLE 0
#define INCLUDE_PROPERTY_HASPRESENTATION 0
#define INCLUDE_PROPERTY_CURRENTPRESENTATION 0
#define INCLUDE_PROPERTY_HASCONTEXT 0
#define INCLUDE_PROPERTY_STARTCONFERENCEFROM 0
#define INCLUDE_PROPERTY_SERVICESTATUS 0
#define INCLUDE_PROPERTY_FROMSERVICEPARAMETER 0
#define INCLUDE_PROPERTY_STOPUPDATESERVICEPAGE 0
#define INCLUDE_PROPERTY_SEARCHVARIABLEPARAMETER 0
#define INCLUDE_PROPERTY_PLACEDESCRIPTION 0
#define INCLUDE_PROPERTY_HASCLIENTURL 0
#define INCLUDE_PROPERTY_VIDEOURL 0
#define INCLUDE_PROPERTY_PLACEFOUNDINGDATE 0
#define INCLUDE_PROPERTY_CURRENTSECTION 0
#define INCLUDE_CLASS_SMARTROOM 0
#define INCLUDE_CLASS_PRESENTATION 0
#define INCLUDE_CLASS_CONFERENCENOTIFICATION 0
#define INCLUDE_CLASS_SEARCHACTIVITYPARAMETER 0
#define INCLUDE_CLASS_ACTIVITY 0
#define INCLUDE_CLASS_PROFILE 0
#define INCLUDE_CLASS_PERSON 0
#define INCLUDE_CLASS_CLIENTNOTIFICATION 0
#define INCLUDE_CLASS_SOCIALPROGRAMNOTIFICATION 0
#define INCLUDE_CLASS_WEBSERVERNOTIFICATION 0
#define INCLUDE_CLASS_DISCUSSIONSERVICE 0
#define INCLUDE_CLASS_SERVICE 0
#define INCLUDE_CLASS_PLACE 0
#define INCLUDE_CLASS_TIMESLOT 0
#define INCLUDE_CLASS_DSNOTIFICATIONPARAMETER 0
#define INCLUDE_CLASS_PRESENTATIONSERVICE 0
#define INCLUDE_CLASS_THING 0
#define INCLUDE_CLASS_CONTENTSERVICE 0
#define INCLUDE_CLASS_AGENDANOTIFICATION 0
#define INCLUDE_CLASS_SOCIALPROGRAM 0
#define INCLUDE_CLASS_PLACESLOT 0
#define INCLUDE_CLASS_CONFERENCESERVICE 0
#define INCLUDE_CLASS_ONLINEACCOUNT 0
#define INCLUDE_CLASS_PHOTO 0
#define INCLUDE_CLASS_SEARCHACTIVITY 0
#define INCLUDE_CLASS_NOTIFICATIONPARAMETER 0
#define INCLUDE_CLASS_SOCIALPROGRAMSERVICE 0
#define INCLUDE_CLASS_NOTHING 0
#define INCLUDE_CLASS_MICROPHONESERVICE 0
#define INCLUDE_CLASS_VIDEO 0
#define INCLUDE_CLASS_SECTION 0
#define INCLUDE_CLASS_CONTEXT 0
#define INCLUDE_CLASS_PRESENTATIONNOTIFICATION 0


#endif


#if INCLUDE_CLASS_SMARTROOM
extern class_t *CLASS_SMARTROOM;
#endif
#if INCLUDE_CLASS_PRESENTATION
extern class_t *CLASS_PRESENTATION;
#endif
#if INCLUDE_CLASS_CONFERENCENOTIFICATION
extern class_t *CLASS_CONFERENCENOTIFICATION;
#endif
#if INCLUDE_CLASS_SEARCHACTIVITYPARAMETER
extern class_t *CLASS_SEARCHACTIVITYPARAMETER;
#endif
#if INCLUDE_CLASS_ACTIVITY
extern class_t *CLASS_ACTIVITY;
#endif
#if INCLUDE_CLASS_PROFILE
extern class_t *CLASS_PROFILE;
#endif
#if INCLUDE_CLASS_PERSON
extern class_t *CLASS_PERSON;
#endif
#if INCLUDE_CLASS_CLIENTNOTIFICATION
extern class_t *CLASS_CLIENTNOTIFICATION;
#endif
#if INCLUDE_CLASS_SOCIALPROGRAMNOTIFICATION
extern class_t *CLASS_SOCIALPROGRAMNOTIFICATION;
#endif
#if INCLUDE_CLASS_WEBSERVERNOTIFICATION
extern class_t *CLASS_WEBSERVERNOTIFICATION;
#endif
#if INCLUDE_CLASS_DISCUSSIONSERVICE
extern class_t *CLASS_DISCUSSIONSERVICE;
#endif
#if INCLUDE_CLASS_SERVICE
extern class_t *CLASS_SERVICE;
#endif
#if INCLUDE_CLASS_PLACE
extern class_t *CLASS_PLACE;
#endif
#if INCLUDE_CLASS_TIMESLOT
extern class_t *CLASS_TIMESLOT;
#endif
#if INCLUDE_CLASS_DSNOTIFICATIONPARAMETER
extern class_t *CLASS_DSNOTIFICATIONPARAMETER;
#endif
#if INCLUDE_CLASS_PRESENTATIONSERVICE
extern class_t *CLASS_PRESENTATIONSERVICE;
#endif
#if INCLUDE_CLASS_THING
extern class_t *CLASS_THING;
#endif
#if INCLUDE_CLASS_CONTENTSERVICE
extern class_t *CLASS_CONTENTSERVICE;
#endif
#if INCLUDE_CLASS_AGENDANOTIFICATION
extern class_t *CLASS_AGENDANOTIFICATION;
#endif
#if INCLUDE_CLASS_SOCIALPROGRAM
extern class_t *CLASS_SOCIALPROGRAM;
#endif
#if INCLUDE_CLASS_PLACESLOT
extern class_t *CLASS_PLACESLOT;
#endif
#if INCLUDE_CLASS_CONFERENCESERVICE
extern class_t *CLASS_CONFERENCESERVICE;
#endif
#if INCLUDE_CLASS_ONLINEACCOUNT
extern class_t *CLASS_ONLINEACCOUNT;
#endif
#if INCLUDE_CLASS_PHOTO
extern class_t *CLASS_PHOTO;
#endif
#if INCLUDE_CLASS_SEARCHACTIVITY
extern class_t *CLASS_SEARCHACTIVITY;
#endif
#if INCLUDE_CLASS_NOTIFICATIONPARAMETER
extern class_t *CLASS_NOTIFICATIONPARAMETER;
#endif
#if INCLUDE_CLASS_SOCIALPROGRAMSERVICE
extern class_t *CLASS_SOCIALPROGRAMSERVICE;
#endif
#if INCLUDE_CLASS_NOTHING
extern class_t *CLASS_NOTHING;
#endif
#if INCLUDE_CLASS_MICROPHONESERVICE
extern class_t *CLASS_MICROPHONESERVICE;
#endif
#if INCLUDE_CLASS_VIDEO
extern class_t *CLASS_VIDEO;
#endif
#if INCLUDE_CLASS_SECTION
extern class_t *CLASS_SECTION;
#endif
#if INCLUDE_CLASS_CONTEXT
extern class_t *CLASS_CONTEXT;
#endif
#if INCLUDE_CLASS_PRESENTATIONNOTIFICATION
extern class_t *CLASS_PRESENTATIONNOTIFICATION;
#endif


#if INCLUDE_PROPERTY_MBOX
extern property_t *PROPERTY_MBOX;
#endif
#if INCLUDE_PROPERTY_SECTIONPARAMETER
extern property_t *PROPERTY_SECTIONPARAMETER;
#endif
#if INCLUDE_PROPERTY_STARTUPDATESERVICEPAGE
extern property_t *PROPERTY_STARTUPDATESERVICEPAGE;
#endif
#if INCLUDE_PROPERTY_SOCIALPROGRAMLATITUDECOORDINATE
extern property_t *PROPERTY_SOCIALPROGRAMLATITUDECOORDINATE;
#endif
#if INCLUDE_PROPERTY_PRESENTATIONURL
extern property_t *PROPERTY_PRESENTATIONURL;
#endif
#if INCLUDE_PROPERTY_CONTENTURL
extern property_t *PROPERTY_CONTENTURL;
#endif
#if INCLUDE_PROPERTY_ORGANIZATION
extern property_t *PROPERTY_ORGANIZATION;
#endif
#if INCLUDE_PROPERTY_PHOTOLONGITUDECOORDINATE
extern property_t *PROPERTY_PHOTOLONGITUDECOORDINATE;
#endif
#if INCLUDE_PROPERTY_SECTIONSTARTTIME
extern property_t *PROPERTY_SECTIONSTARTTIME;
#endif
#if INCLUDE_PROPERTY_VIDEOTITLE
extern property_t *PROPERTY_VIDEOTITLE;
#endif
#if INCLUDE_PROPERTY_PHOTOTHUMBNAILURL
extern property_t *PROPERTY_PHOTOTHUMBNAILURL;
#endif
#if INCLUDE_PROPERTY_ENDPRESENTATION
extern property_t *PROPERTY_ENDPRESENTATION;
#endif
#if INCLUDE_PROPERTY_CURRENTSLIDENUM
extern property_t *PROPERTY_CURRENTSLIDENUM;
#endif
#if INCLUDE_PROPERTY_STOPSEARCH
extern property_t *PROPERTY_STOPSEARCH;
#endif
#if INCLUDE_PROPERTY_HOLDSACTIVITY
extern property_t *PROPERTY_HOLDSACTIVITY;
#endif
#if INCLUDE_PROPERTY_STARTSERVICEMODE
extern property_t *PROPERTY_STARTSERVICEMODE;
#endif
#if INCLUDE_PROPERTY_PHOTOLATITUDECOORDINATE
extern property_t *PROPERTY_PHOTOLATITUDECOORDINATE;
#endif
#if INCLUDE_PROPERTY_ACTIVITYTITLE
extern property_t *PROPERTY_ACTIVITYTITLE;
#endif
#if INCLUDE_PROPERTY_VOTEUPDATE
extern property_t *PROPERTY_VOTEUPDATE;
#endif
#if INCLUDE_PROPERTY_USERNAME
extern property_t *PROPERTY_USERNAME;
#endif
#if INCLUDE_PROPERTY_PHOTOURL
extern property_t *PROPERTY_PHOTOURL;
#endif
#if INCLUDE_PROPERTY_PHOTOTITLE
extern property_t *PROPERTY_PHOTOTITLE;
#endif
#if INCLUDE_PROPERTY_TIMESLOTACTUALDURATION
extern property_t *PROPERTY_TIMESLOTACTUALDURATION;
#endif
#if INCLUDE_PROPERTY_TOPIC_INTEREST
extern property_t *PROPERTY_TOPIC_INTEREST;
#endif
#if INCLUDE_PROPERTY_PASSWORD
extern property_t *PROPERTY_PASSWORD;
#endif
#if INCLUDE_PROPERTY_PLACESLOTMINUSRATING
extern property_t *PROPERTY_PLACESLOTMINUSRATING;
#endif
#if INCLUDE_PROPERTY_HASVIDEO
extern property_t *PROPERTY_HASVIDEO;
#endif
#if INCLUDE_PROPERTY_TIMESLOTTITLE
extern property_t *PROPERTY_TIMESLOTTITLE;
#endif
#if INCLUDE_PROPERTY_HASPRESENTATIONSERVICEURL
extern property_t *PROPERTY_HASPRESENTATIONSERVICEURL;
#endif
#if INCLUDE_PROPERTY_SECTIONACTUALSTARTTIME
extern property_t *PROPERTY_SECTIONACTUALSTARTTIME;
#endif
#if INCLUDE_PROPERTY_SOCIALPROGRAMTITLE
extern property_t *PROPERTY_SOCIALPROGRAMTITLE;
#endif
#if INCLUDE_PROPERTY_PHONE
extern property_t *PROPERTY_PHONE;
#endif
#if INCLUDE_PROPERTY_UPDATESERVICEINFORMATION
extern property_t *PROPERTY_UPDATESERVICEINFORMATION;
#endif
#if INCLUDE_PROPERTY_STARTCONFERENCE
extern property_t *PROPERTY_STARTCONFERENCE;
#endif
#if INCLUDE_PROPERTY_PLACESLOTPLUSRATING
extern property_t *PROPERTY_PLACESLOTPLUSRATING;
#endif
#if INCLUDE_PROPERTY_CURRENTSLIDECOUNT
extern property_t *PROPERTY_CURRENTSLIDECOUNT;
#endif
#if INCLUDE_PROPERTY_PLACESLOTRATING
extern property_t *PROPERTY_PLACESLOTRATING;
#endif
#if INCLUDE_PROPERTY_HASSERVICE
extern property_t *PROPERTY_HASSERVICE;
#endif
#if INCLUDE_PROPERTY_SECTIONTITLE
extern property_t *PROPERTY_SECTIONTITLE;
#endif
#if INCLUDE_PROPERTY_PERSONINFORMATION
extern property_t *PROPERTY_PERSONINFORMATION;
#endif
#if INCLUDE_PROPERTY_CURRENTSLIDEIMG
extern property_t *PROPERTY_CURRENTSLIDEIMG;
#endif
#if INCLUDE_PROPERTY_NEXTTIMESLOT
extern property_t *PROPERTY_NEXTTIMESLOT;
#endif
#if INCLUDE_PROPERTY_TIMESLOTSPEAKERNAME
extern property_t *PROPERTY_TIMESLOTSPEAKERNAME;
#endif
#if INCLUDE_PROPERTY_PLACEHASRELATION
extern property_t *PROPERTY_PLACEHASRELATION;
#endif
#if INCLUDE_PROPERTY_STOPSERVICEMODE
extern property_t *PROPERTY_STOPSERVICEMODE;
#endif
#if INCLUDE_PROPERTY_PORT
extern property_t *PROPERTY_PORT;
#endif
#if INCLUDE_PROPERTY_PLACEHASPHOTO
extern property_t *PROPERTY_PLACEHASPHOTO;
#endif
#if INCLUDE_PROPERTY_PRESENTATIONTITLE
extern property_t *PROPERTY_PRESENTATIONTITLE;
#endif
#if INCLUDE_PROPERTY_TIMESLOTPARAMETER
extern property_t *PROPERTY_TIMESLOTPARAMETER;
#endif
#if INCLUDE_PROPERTY_HASSECTION
extern property_t *PROPERTY_HASSECTION;
#endif
#if INCLUDE_PROPERTY_FIRSTTIMESLOT
extern property_t *PROPERTY_FIRSTTIMESLOT;
#endif
#if INCLUDE_PROPERTY_STARTVIDEO
extern property_t *PROPERTY_STARTVIDEO;
#endif
#if INCLUDE_PROPERTY_STARTSEARCH
extern property_t *PROPERTY_STARTSEARCH;
#endif
#if INCLUDE_PROPERTY_SOCIALPROGRAMPRESENTPLACESLOT
extern property_t *PROPERTY_SOCIALPROGRAMPRESENTPLACESLOT;
#endif
#if INCLUDE_PROPERTY_SERVICENAME
extern property_t *PROPERTY_SERVICENAME;
#endif
#if INCLUDE_PROPERTY_PLACELONGITUDECOORDINATE
extern property_t *PROPERTY_PLACELONGITUDECOORDINATE;
#endif
#if INCLUDE_PROPERTY_NAME
extern property_t *PROPERTY_NAME;
#endif
#if INCLUDE_PROPERTY_PRESENTATIONTAGS
extern property_t *PROPERTY_PRESENTATIONTAGS;
#endif
#if INCLUDE_PROPERTY_CITY
extern property_t *PROPERTY_CITY;
#endif
#if INCLUDE_PROPERTY_STARTPRESENTATION
extern property_t *PROPERTY_STARTPRESENTATION;
#endif
#if INCLUDE_PROPERTY_CURRENTTIMESLOT
extern property_t *PROPERTY_CURRENTTIMESLOT;
#endif
#if INCLUDE_PROPERTY_PHOTODESCRIPTION
extern property_t *PROPERTY_PHOTODESCRIPTION;
#endif
#if INCLUDE_PROPERTY_SHOWSLIDE
extern property_t *PROPERTY_SHOWSLIDE;
#endif
#if INCLUDE_PROPERTY_IP
extern property_t *PROPERTY_IP;
#endif
#if INCLUDE_PROPERTY_HASSERVICEPARAMETER
extern property_t *PROPERTY_HASSERVICEPARAMETER;
#endif
#if INCLUDE_PROPERTY_CURRENTSOCIALPROGRAM
extern property_t *PROPERTY_CURRENTSOCIALPROGRAM;
#endif
#if INCLUDE_PROPERTY_UPDATEPRESENTATION
extern property_t *PROPERTY_UPDATEPRESENTATION;
#endif
#if INCLUDE_PROPERTY_PHOTOMEDIUMURL
extern property_t *PROPERTY_PHOTOMEDIUMURL;
#endif
#if INCLUDE_PROPERTY_STOPVIDEO
extern property_t *PROPERTY_STOPVIDEO;
#endif
#if INCLUDE_PROPERTY_ENDCONFERENCE
extern property_t *PROPERTY_ENDCONFERENCE;
#endif
#if INCLUDE_PROPERTY_SERVICEDESCRIPTION
extern property_t *PROPERTY_SERVICEDESCRIPTION;
#endif
#if INCLUDE_PROPERTY_PLACEPARAMETER
extern property_t *PROPERTY_PLACEPARAMETER;
#endif
#if INCLUDE_PROPERTY_TIMESLOTPERSON
extern property_t *PROPERTY_TIMESLOTPERSON;
#endif
#if INCLUDE_PROPERTY_NOTIFICATIONNUMBERPARAMETER
extern property_t *PROPERTY_NOTIFICATIONNUMBERPARAMETER;
#endif
#if INCLUDE_PROPERTY_SHOWSUMMARYSLIDE
extern property_t *PROPERTY_SHOWSUMMARYSLIDE;
#endif
#if INCLUDE_PROPERTY_SOCIALPROGRAMLONGITUDECOORDINATE
extern property_t *PROPERTY_SOCIALPROGRAMLONGITUDECOORDINATE;
#endif
#if INCLUDE_PROPERTY_STATUS
extern property_t *PROPERTY_STATUS;
#endif
#if INCLUDE_PROPERTY_WLANMAC
extern property_t *PROPERTY_WLANMAC;
#endif
#if INCLUDE_PROPERTY_TIMESLOTPRESENTATION
extern property_t *PROPERTY_TIMESLOTPRESENTATION;
#endif
#if INCLUDE_PROPERTY_ACCOUNT
extern property_t *PROPERTY_ACCOUNT;
#endif
#if INCLUDE_PROPERTY_TIMESLOTDURATION
extern property_t *PROPERTY_TIMESLOTDURATION;
#endif
#if INCLUDE_PROPERTY_SECTIONDATE
extern property_t *PROPERTY_SECTIONDATE;
#endif
#if INCLUDE_PROPERTY_AGE
extern property_t *PROPERTY_AGE;
#endif
#if INCLUDE_PROPERTY_UPDATEAGENDA
extern property_t *PROPERTY_UPDATEAGENDA;
#endif
#if INCLUDE_PROPERTY_SEARCHTYPEPARAMETER
extern property_t *PROPERTY_SEARCHTYPEPARAMETER;
#endif
#if INCLUDE_PROPERTY_IMG
extern property_t *PROPERTY_IMG;
#endif
#if INCLUDE_PROPERTY_PRESENTSOCIALPROGRAM
extern property_t *PROPERTY_PRESENTSOCIALPROGRAM;
#endif
#if INCLUDE_PROPERTY_HASAGENDASERVICEURL
extern property_t *PROPERTY_HASAGENDASERVICEURL;
#endif
#if INCLUDE_PROPERTY_PLACELATITUDECOORDINATE
extern property_t *PROPERTY_PLACELATITUDECOORDINATE;
#endif
#if INCLUDE_PROPERTY_PLACESLOTPRESENTPLACE
extern property_t *PROPERTY_PLACESLOTPRESENTPLACE;
#endif
#if INCLUDE_PROPERTY_SERVICEINFORMATIONPARAMETER
extern property_t *PROPERTY_SERVICEINFORMATIONPARAMETER;
#endif
#if INCLUDE_PROPERTY_LANGUAGE
extern property_t *PROPERTY_LANGUAGE;
#endif
#if INCLUDE_PROPERTY_PLACETITLE
extern property_t *PROPERTY_PLACETITLE;
#endif
#if INCLUDE_PROPERTY_HASPRESENTATION
extern property_t *PROPERTY_HASPRESENTATION;
#endif
#if INCLUDE_PROPERTY_CURRENTPRESENTATION
extern property_t *PROPERTY_CURRENTPRESENTATION;
#endif
#if INCLUDE_PROPERTY_HASCONTEXT
extern property_t *PROPERTY_HASCONTEXT;
#endif
#if INCLUDE_PROPERTY_STARTCONFERENCEFROM
extern property_t *PROPERTY_STARTCONFERENCEFROM;
#endif
#if INCLUDE_PROPERTY_SERVICESTATUS
extern property_t *PROPERTY_SERVICESTATUS;
#endif
#if INCLUDE_PROPERTY_FROMSERVICEPARAMETER
extern property_t *PROPERTY_FROMSERVICEPARAMETER;
#endif
#if INCLUDE_PROPERTY_STOPUPDATESERVICEPAGE
extern property_t *PROPERTY_STOPUPDATESERVICEPAGE;
#endif
#if INCLUDE_PROPERTY_SEARCHVARIABLEPARAMETER
extern property_t *PROPERTY_SEARCHVARIABLEPARAMETER;
#endif
#if INCLUDE_PROPERTY_PLACEDESCRIPTION
extern property_t *PROPERTY_PLACEDESCRIPTION;
#endif
#if INCLUDE_PROPERTY_HASCLIENTURL
extern property_t *PROPERTY_HASCLIENTURL;
#endif
#if INCLUDE_PROPERTY_VIDEOURL
extern property_t *PROPERTY_VIDEOURL;
#endif
#if INCLUDE_PROPERTY_PLACEFOUNDINGDATE
extern property_t *PROPERTY_PLACEFOUNDINGDATE;
#endif
#if INCLUDE_PROPERTY_CURRENTSECTION
extern property_t *PROPERTY_CURRENTSECTION;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */
